### ISSUE TITLE
Make greeting dynamic

### ISSUE THREAD

**Issue by Jamy-ai** [vimal-ai/ellis#1]
When I say "hi" to ellis, she always says "hi vimal". She should take name of the user.
![ellisGreetIssue](https://user-images.githubusercontent.com/73168961/101876913-3b990180-3bb3-11eb-9360-7af6f89f28b0.png)

**Comment by Jamy-ai** [comment]
I want to work on this issue.

**Comment by mahavirbha** [comment]
> When I say "hi" to ellis, she always says "hi vimal". She should take name of the user.
> ![ellisGreetIssue](https://user-images.githubusercontent.com/73168961/101876913-3b990180-3bb3-11eb-9360-7af6f89f28b0.png)

also she's displaying such kind of attitude!
![Screenshot from 2020-12-11 13-34-33](https://user-images.githubusercontent.com/70435819/101879939-1f4b9380-3bb8-11eb-98c9-3765ece81d99.png)

**Comment by Jamy-ai** [comment]
issue solved at #3

**Comment by vimal-ai** [comment]
Good Job
